# Generated by Django 4.2.11 on 2024-05-09 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('m2_built', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m2_totals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_parking_lots', models.PositiveIntegerField()),
                ('qty_rooms', models.PositiveIntegerField()),
                ('qty_bathrooms', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_rental_app.typeuser')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='properties_rental_app.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='properties_rental_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties_rental_app.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='id_type_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='properties_rental_app.typeproperty'),
        ),
    ]
