# Generated by Django 4.2.11 on 2024-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
