# Generated by Django 4.2.11 on 2024-05-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties_rental_app', '0002_property_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='county',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_rental_app.state')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='id_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_rental_app.county')),
    ]
