# Generated by Django 4.2.11 on 2024-05-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_rental_app', '0003_state_remove_property_county_remove_property_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
