# Generated by Django 4.2.11 on 2024-05-16 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties_rental_app', '0004_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_rental_app.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='typeproperty',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Property of Type'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_rental_app.typeuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='properties_rental_app.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
