# Generated by Django 4.2.11 on 2024-05-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties_rental_app', '0005_alter_county_id_state_alter_county_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessorProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties_rental_app.userprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessors', to='properties_rental_app.property')),
            ],
        ),
    ]
